"""add email verification

Revision ID: bda841614666
Revises: 
Create Date: 2026-05-23 09:22:04.453699

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bda841614666'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('interview_messages')
    with op.batch_alter_table('interview_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('session_id', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('position_label', sa.String(length=200), nullable=False))
        batch_op.add_column(sa.Column('company', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('language', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('total_questions', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('questions_json', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('audio_path', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('transcript', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('score_total', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('score_clarity', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('score_structure', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('score_confidence', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('score_relevance', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('score_vocabulary', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('score_fluency', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('feedback_json', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('suggestions', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('strengths', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('weaknesses', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('duration_seconds', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_interview_sessions_session_id'), ['session_id'], unique=False)
        batch_op.drop_column('job_position')
        batch_op.drop_column('current_question')
        batch_op.drop_column('difficulty')
        batch_op.drop_column('interview_type')
        batch_op.drop_column('total_score')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_verified', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('last_login', sa.DateTime(), nullable=True))
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=256),
               nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=256),
               nullable=False)
        batch_op.drop_column('last_login')
        batch_op.drop_column('is_verified')

    with op.batch_alter_table('interview_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_score', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('interview_type', sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('difficulty', sa.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('current_question', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('job_position', sa.VARCHAR(length=255), nullable=True))
        batch_op.drop_index(batch_op.f('ix_interview_sessions_session_id'))
        batch_op.drop_column('duration_seconds')
        batch_op.drop_column('weaknesses')
        batch_op.drop_column('strengths')
        batch_op.drop_column('suggestions')
        batch_op.drop_column('feedback_json')
        batch_op.drop_column('score_fluency')
        batch_op.drop_column('score_vocabulary')
        batch_op.drop_column('score_relevance')
        batch_op.drop_column('score_confidence')
        batch_op.drop_column('score_structure')
        batch_op.drop_column('score_clarity')
        batch_op.drop_column('score_total')
        batch_op.drop_column('transcript')
        batch_op.drop_column('audio_path')
        batch_op.drop_column('questions_json')
        batch_op.drop_column('total_questions')
        batch_op.drop_column('language')
        batch_op.drop_column('company')
        batch_op.drop_column('position_label')
        batch_op.drop_column('session_id')

    op.create_table('interview_messages',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('session_id', sa.INTEGER(), nullable=True),
    sa.Column('role', sa.VARCHAR(length=20), nullable=True),
    sa.Column('question', sa.TEXT(), nullable=True),
    sa.Column('answer', sa.TEXT(), nullable=True),
    sa.Column('feedback', sa.TEXT(), nullable=True),
    sa.Column('score', sa.FLOAT(), nullable=True),
    sa.Column('audio_path', sa.VARCHAR(length=500), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['interview_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
